name: 问题与 BUG 反馈
description: 问题反馈必须使用此模板进行提交
labels: [ bug ]
title: "[问题与 BUG 反馈] (在这里简要描述问题原因)"
body:
  - type: markdown
    attributes:
      value: |
        ### 请在下方填写问题发生的具体原因和复现步骤。
        
        我们只接受 MIUI 或 HyperOS 正规官方版本系统，如果你正在使用官改 (第三方修改版) 请不要提交任何 BUG 与问题，我们无义务去解决，请自求多福。
        
        发生异常、崩溃、闪退或功能性问题，必须提交问题 Log (日志)，没有 Log 的 issues 将直接被关闭。
  - type: input
    attributes:
      label: 模块版本
      description: 请填写当前使用的模块完整版本号，例如：**2.0**
    validations:
      required: true
  - type: input
    attributes:
      label: 系统版本
      description: |
        这里填写当前的系统，例如：**MIUI 13.0.1** 或 **HyperOS 1.0**
        开发版需要标注具体的版本号，例如：**MIUI 13 22.9.27** 或 **HyperOS 1.0 22.9.27**
    validations:
      required: true
  - type: dropdown
    attributes:
      label: 系统版本类型
      description: 请选择你使用的系统版本类型。
      options:
        - 稳定版
        - 稳定内测版
        - 开发版
        - 开发内测版
        - 开发公测版 DEV
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Android 版本
      options:
        - 15
        - 14
        - 13
        - 12L/12.1
        - 12
        - 11
        - 10
        - 9
        - 8.1
        - 8.0.0
    validations:
      required: true
  - type: input
    attributes:
      label: Xposed 框架名称与版本号
      description: 请填写当前使用的 Xposed 框架，例如：**LSPosed 1.8.4(次版本号)**
    validations:
      required: true
  - type: input
    attributes:
      label: 与系统界面(系统 UI)同作用域的 Xposed 模块
      description: |
        此模块的作用域为系统界面(系统 UI)，为确保非其它模块冲突造成的问题，请一定要填写当前你同时激活的相关模块。
        若没有，请直接在下方填写“无”。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 详细描述问题发生的具体原因
      description: 请在下方详细描述问题发生的具体场景、复现步骤和经过，以便我们能够按照你所描述的步骤复现这个问题。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 提供模块问题 Log 或必要 Log
      description: LSPosed 可在日志管理中查看并筛选包含 `MIUINativeNotifyIcon` 的日志。
      value: |
        <details><summary>展开查看</summary><pre><code>

        (此处粘贴问题 Log)

        </code></pre></details>
        <!-- 提交时请将括号内容包括括号全部删除，粘贴你复制的日志，不要破坏代码格式 -->
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: 确认一下你提交的信息
      description: |
        为了确保 issues 的质量和避免浪费不必要的时间，未勾选下方选项的 issues 将直接被关闭。
        请一定确保你已经**勾选下方的选项**后再提交。
      options:
        - label: 我确保上述信息准确无误
          required: false
